# Create Data Splits
def create_splits(team_data,r):
    # Libraries
    import pandas as pd

    # Create Response
    team_data['Outcome'] = 0
    team_data.loc[team_data['Round']<r,'Outcome'] = 0
    team_data.loc[team_data['Round']>=r,'Outcome'] = 1

    # Cols to Drop
    round_drops_pre = {
        2:['Team','Round','Year','First_Year','Region',
           'Tempo','RankTempo','AdjTempo','Def_3',
           'RankOff_1','RankDef_1','Def_1','Off_2',
           'Winner_Actual_Full','Winner_Actual_6'],
        3:['Team','Round'],
        4:['Team','Round'],
        5:['Team','Round','Year','First_Year',
           'Tempo','DE','RankAdjTempo','AdjTempo',
           'Off_3','RankOff_3','Off_2','RankDef_1','RankDef_2','Def_3',
            'R32_Actual_Full','R32_Actual_6',
           'F4_Actual_Full','F4_Actual_6',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        6:['Team','Round','Year','First_Year','Conf Tourney',
           'RankOff_1','RankOff_2',
           'S16_Actual_12',
           'F4_Actual_6'],
        7:['Team','Round'],
    }
    # Drop Cols
    data_sub = team_data.drop(columns=round_drops_pre[r])

    # Dummy Vars
    if 'Conf' in data_sub.columns:
        # Conference
        data_sub = pd.concat([data_sub, pd.get_dummies(data_sub['Conf'], prefix='Conf')], axis=1)
        data_sub.drop(columns='Conf', inplace=True)
    # Region
    if 'Region' in data_sub.columns:
        data_sub = pd.concat([data_sub, pd.get_dummies(data_sub['Region'], prefix='Region')], axis=1)
        data_sub.drop(columns='Region', inplace=True)
    
    # Drop Any Unwanted Dummy Cols
    round_drops_post = {
        2:['Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_Southland','Conf_ACC','Conf_Big 12','Conf_MAC',
           'Conf_CUSA','Conf_MAAC','Conf_Big South','Conf_SWAC','Conf_A-Sun','Conf_Sun Belt','Conf_Big West',
           'Conf_CAA','Conf_Big Sky','Conf_OVC','Conf_Summit','Conf_NEC','Conf_Big East','Conf_WCC',
           'Conf_AAC','Conf_A-10','Conf_Horizon','Conf_Ivy'],
      3:[],
        4:[],
        5:['Conf_Pac-12','Conf_Southland','Conf_Pac-10','Conf_Pac-10','Conf_MEAC','Conf_MAC','Conf_Patriot',
           'Conf_CUSA','Conf_Big Sky','Conf_Big West','Conf_Sun Belt','Conf_A-Sun','Conf_AEC','Conf_Summit',
           'Conf_WAC','Conf_MAAC','Conf_Big Ten','Conf_MVC','Conf_CAA','Conf_Big East','Conf_Ivy','Conf_NEC',
            'Conf_AAC','Conf_OVC','Conf_MWC','Conf_Big South','Conf_SWAC','Conf_Southern','Conf_Big 12',
           'Region_West'],
        6:['Conf_CUSA','Conf_MVC','Conf_Southland','Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_MAC',
           'Conf_Big West','Conf_Summit','Conf_Big Sky','Conf_CAA','Conf_Sun Belt','Conf_A-Sun',
           'Conf_WAC','Conf_Patriot','Conf_MAAC','Conf_SWAC','Conf_Southern','Conf_Ivy','Conf_NEC','Conf_AEC',
            'Conf_Big South','Conf_OVC','Conf_AAC','Conf_MWC',
           'Region_East','Region_South'],
        7:[]
        }
    data_sub = data_sub.drop(columns=round_drops_post[r])

    # Testing & Training Splits
    X = data_sub.drop(columns='Outcome')
    y = data_sub['Outcome']
    return X, y

    # > 0.0001
    round_drops_pre = {
        2:['Team','Round','Year','First_Year','Region',
           'Tempo','RankTempo','AdjTempo','Def_3',
           'RankOff_1','RankDef_1','Def_1','Off_2',
           'Winner_Actual_Full','Winner_Actual_6'],
        3:['Team','Round','Year','First_Year',
           'Def_2',
           'R32_Actual_6'],
        4:['Team','Round','Year','First_Year',
           'RankDE',
           'Off_3'],
        5:['Team','Round','Year','First_Year',
           'Off_3'],
        6:['Team','Round','Year','First_Year',
           'RankOff_1',
           'F4_Actual_6'],
        7:['Team','Round','Year','First_Year',
           'OE','RankDE',
           'Off_1','Def_3',
           'R32_Actual_Full'],
    }
    round_drops_post = {
        2:['Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_Southland','Conf_ACC','Conf_Big 12','Conf_MAC',
           'Conf_CUSA','Conf_MAAC','Conf_Big South','Conf_SWAC','Conf_A-Sun','Conf_Sun Belt','Conf_Big West',
           'Conf_CAA','Conf_Big Sky','Conf_OVC','Conf_Summit','Conf_NEC','Conf_Big East','Conf_WCC',
           'Conf_AAC','Conf_A-10','Conf_Horizon','Conf_Ivy'],
        3:['Conf_MEAC','Conf_Mid-Cont','Conf_Southland','Conf_Pac-10','Conf_Patriot','Conf_A-Sun',
           'Conf_Big West','Conf_SWAC','Conf_CUSA','Conf_Sun Belt','Conf_NEC','Conf_AEC','Conf_MAC',
           'Conf_Southern','Conf_OVC','Conf_CAA','Conf_MAAC'],
        4:['Conf_MVC','Conf_Southern','Conf_MAC','Conf_Pac-10','Conf_Southland','Conf_MEAC','Conf_Mid-Cont',
           'Conf_Big Ten','Conf_A-Sun'],
        5:['Conf_Pac-12','Conf_Southland','Conf_Pac-10','Conf_Pac-10','Conf_MEAC','Conf_MAC','Conf_Patriot',
           'Conf_CUSA','Conf_Big Sky',
           'Region_West'],
        6:['Conf_CUSA','Conf_MVC','Conf_Southland','Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_MAC',
           'Conf_Big West','Conf_Summit','Conf_Big Sky','Conf_CAA','Conf_Sun Belt','Conf_A-Sun',
           'Conf_WAC','Conf_Patriot','Conf_MAAC','Conf_SWAC','Conf_Southern','Conf_Ivy'],
        7:['Conf_Pac-12','Conf_CUSA','Conf_Patriot','Conf_SWAC','Conf_MAAC','Conf_AEC','Conf_Ivy','Conf_WAC',
           'Conf_NEC','Conf_Big South','Conf_Horizon','Conf_MVC','Conf_MEAC','Conf_Pac-10','Conf_Mid-Cont',
            'Conf_Southland','Conf_OVC','Conf_Big Sky','Conf_Sun Belt','Conf_Big West','Conf_Summit',
            'Conf_A-Sun','Conf_Southern','Conf_CAA','Conf_MAC','Conf_AAC','Conf_MWC','Conf_A-10',
           'Region_East']
        }
    
    # > 0.00025
    round_drops_pre = {
        2:['Team','Round','Year','First_Year','Region','Wins',
           'Tempo','RankTempo','AdjTempo','DE','RankAdjTempo',
           'Def_3','RankOff_1','RankDef_1','Def_1','Off_2','Off_1','RankDef_3','Def_2','RankOff_3','RankOff_2',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        3:['Team','Round','Year','First_Year',
           'AdjDE',
           'Def_2',
           'R32_Actual_6',
           'Winner_Actual_Full','Winner_Actual_6'],
        4:['Team','Round','Year','First_Year',
           'RankDE',
           'Off_3','Off_2','Def_2',
           'S16_Actual_Full',
           'NCG_Actual_6'],
        5:['Team','Round','Year','First_Year',
           'Off_3',
           'F4_Actual_6',
           'Winner_Actual_12'],
        6:['Team','Round','Year','First_Year','Conf Tourney',
           'RankOff_1','RankOff_2',
           'S16_Actual_12',
           'F4_Actual_6'],
        7:['Team','Round','Year','First_Year',
           'OE','RankDE',
           'Off_1','Def_3','Off_2','RankDef_2','RankDef_3','RankOff_2',
           'R32_Actual_Full',
           'E8_Actual_Full'],
    }
    round_drops_post = {
        2:['Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_Southland','Conf_ACC','Conf_Big 12','Conf_MAC',
           'Conf_CUSA','Conf_MAAC','Conf_Big South','Conf_SWAC','Conf_A-Sun','Conf_Sun Belt','Conf_Big West',
           'Conf_CAA','Conf_Big Sky','Conf_OVC','Conf_Summit','Conf_NEC','Conf_Big East','Conf_WCC',
           'Conf_AAC','Conf_A-10','Conf_Horizon','Conf_Ivy','Conf_MVC','Conf_SEC','Conf_WAC','Conf_Southern',
           'Conf_AEC','Conf_Patriot'],
        3:['Conf_MEAC','Conf_Mid-Cont','Conf_Southland','Conf_Pac-10','Conf_Patriot','Conf_A-Sun',
           'Conf_Big West','Conf_SWAC','Conf_CUSA','Conf_Sun Belt','Conf_NEC','Conf_AEC','Conf_MAC',
           'Conf_Southern','Conf_OVC','Conf_CAA','Conf_MAAC','Conf_Ivy','Conf_Horizon','Conf_Big South',
           'Conf_WAC','Conf_Summit','Conf_MWC','Conf_Big Sky'],
        4:['Conf_MVC','Conf_Southern','Conf_MAC','Conf_Pac-10','Conf_Southland','Conf_MEAC','Conf_Mid-Cont',
           'Conf_Big Ten','Conf_A-Sun','Conf_CAA','Conf_A-10','Conf_AEC','Conf_Patriot','Conf_CUSA','Conf_Big West',
           'Conf_MAAC','Conf_WAC','Conf_Big Sky',
           'Region_Midwest'],
        5:['Conf_Pac-12','Conf_Southland','Conf_Pac-10','Conf_Pac-10','Conf_MEAC','Conf_MAC','Conf_Patriot',
           'Conf_CUSA','Conf_Big Sky','Conf_Big West','Conf_Sun Belt','Conf_A-Sun','Conf_AEC','Conf_Summit',
           'Conf_WAC','Conf_MAAC',
           'Region_West'],
        6:['Conf_CUSA','Conf_MVC','Conf_Southland','Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_MAC',
           'Conf_Big West','Conf_Summit','Conf_Big Sky','Conf_CAA','Conf_Sun Belt','Conf_A-Sun',
           'Conf_WAC','Conf_Patriot','Conf_MAAC','Conf_SWAC','Conf_Southern','Conf_Ivy','Conf_NEC','Conf_AEC',
            'Conf_Big South','Conf_OVC','Conf_AAC','Conf_MWC',
           'Region_East','Region_South'],
        7:['Conf_Pac-12','Conf_CUSA','Conf_Patriot','Conf_SWAC','Conf_MAAC','Conf_AEC','Conf_Ivy','Conf_WAC',
           'Conf_NEC','Conf_Big South','Conf_Horizon','Conf_MVC','Conf_MEAC','Conf_Pac-10','Conf_Mid-Cont',
            'Conf_Southland','Conf_OVC','Conf_Big Sky','Conf_Sun Belt','Conf_Big West','Conf_Summit',
            'Conf_A-Sun','Conf_Southern','Conf_CAA','Conf_MAC','Conf_AAC','Conf_MWC','Conf_A-10','Conf_Big East',
            'Conf_Big 12',
           'Region_East']
        }
    
    # > 0.0005
    round_drops_pre = {
        2:['Team','Round','Year','First_Year','Region','Wins','Conf Tourney',
           'Tempo','RankTempo','AdjTempo','DE','RankAdjTempo','RankOE',
           'Def_3','RankOff_1','RankDef_1','Def_1','Off_2','Off_1','RankDef_3','Def_2','RankOff_3','RankOff_2',
           'Off_3',
           'F4_Actual_6',
           'NCG_Actual_Full',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        3:['Team','Round','Year','First_Year',
           'AdjDE','RankAdjTempo','RankOE',
           'Def_2',
           'R32_Actual_12','R32_Actual_6',
           'E8_Actual_12',
           'NCG_Actual_Full',
           'Winner_Actual_Full','Winner_Actual_6'],
        4:['Team','Round','Year','First_Year',
           'RankDE','RankAdjDE',
           'Off_3','Off_2','Def_2','RankDef_3','Def_3',
           'R32_Actual_Full',
           'S16_Actual_Full',
           'E8_Actual_12','E8_Actual_6',
           'F4_Actual_Full',
           'NCG_Actual_6',
           'Winner_Actual_Full'],
        5:['Team','Round','Year','First_Year',
           'Tempo','DE',
           'Off_3',
           'F4_Actual_6',
           'R32_Actual_Full',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        6:['Team','Round','Year','First_Year','Conf Tourney',
           'DE','AdjEM',
           'RankOff_1','RankOff_2','Off_2','RankOff_3','Def_2','RankDef_1',
           'S16_Actual_12',
           'F4_Actual_6'],
        7:['Team','Round','Year','First_Year','Seed',
           'OE','RankDE','RankAdjDE',
           'Off_1','Def_3','Off_2','RankDef_2','RankDef_3','RankOff_2','Off_3','Def_1',
           'RankOff_3',
           'R32_Actual_Full',
           'S16_Actual_6',
           'E8_Actual_Full'],
    }
    round_drops_post = {
        2:['Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_Southland','Conf_ACC','Conf_Big 12','Conf_MAC',
           'Conf_CUSA','Conf_MAAC','Conf_Big South','Conf_SWAC','Conf_A-Sun','Conf_Sun Belt','Conf_Big West',
           'Conf_CAA','Conf_Big Sky','Conf_OVC','Conf_Summit','Conf_NEC','Conf_Big East','Conf_WCC',
           'Conf_AAC','Conf_A-10','Conf_Horizon','Conf_Ivy','Conf_MVC','Conf_SEC','Conf_WAC','Conf_Southern',
           'Conf_AEC','Conf_Patriot','Conf_Big Ten','Conf_Pac-12','Conf_MWC'],
       3:['Conf_MEAC','Conf_Mid-Cont','Conf_Southland','Conf_Pac-10','Conf_Patriot','Conf_A-Sun',
           'Conf_Big West','Conf_SWAC','Conf_CUSA','Conf_Sun Belt','Conf_NEC','Conf_AEC','Conf_MAC',
           'Conf_Southern','Conf_OVC','Conf_CAA','Conf_MAAC','Conf_Ivy','Conf_Horizon','Conf_Big South',
           'Conf_WAC','Conf_Summit','Conf_MWC','Conf_Big Sky','Conf_Big Ten','Conf_MVC',
           'Region_South'],
        4:['Conf_MVC','Conf_Southern','Conf_MAC','Conf_Pac-10','Conf_Southland','Conf_MEAC','Conf_Mid-Cont',
           'Conf_Big Ten','Conf_A-Sun','Conf_CAA','Conf_A-10','Conf_AEC','Conf_Patriot','Conf_CUSA','Conf_Big West',
           'Conf_MAAC','Conf_WAC','Conf_Big Sky','Conf_Big 12','Conf_MWC','Conf_NEC','Conf_Big South',
           'Conf_ACC','Conf_SWAC','Conf_Ivy','Conf_Summit','Conf_OVC','Conf_Sun Belt',
           'Region_Midwest'],
        5:['Conf_Pac-12','Conf_Southland','Conf_Pac-10','Conf_Pac-10','Conf_MEAC','Conf_MAC','Conf_Patriot',
           'Conf_CUSA','Conf_Big Sky','Conf_Big West','Conf_Sun Belt','Conf_A-Sun','Conf_AEC','Conf_Summit',
           'Conf_WAC','Conf_MAAC','Conf_Big Ten','Conf_MVC','Conf_CAA','Conf_Big East','Conf_Ivy','Conf_NEC',
            'Conf_AAC','Conf_OVC','Conf_MWC','Conf_Big South','Conf_SWAC','Conf_Southern',
           'Region_West'],
        6:['Conf_CUSA','Conf_MVC','Conf_Southland','Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_MAC',
           'Conf_Big West','Conf_Summit','Conf_Big Sky','Conf_CAA','Conf_Sun Belt','Conf_A-Sun',
           'Conf_WAC','Conf_Patriot','Conf_MAAC','Conf_SWAC','Conf_Southern','Conf_Ivy','Conf_NEC','Conf_AEC',
            'Conf_Big South','Conf_OVC','Conf_AAC','Conf_MWC','Conf_ACC','Conf_A-10','Conf_Big 12',
           'Region_East','Region_South'],
        7:['Conf_Pac-12','Conf_CUSA','Conf_Patriot','Conf_SWAC','Conf_MAAC','Conf_AEC','Conf_Ivy','Conf_WAC',
           'Conf_NEC','Conf_Big South','Conf_Horizon','Conf_MVC','Conf_MEAC','Conf_Pac-10','Conf_Mid-Cont',
            'Conf_Southland','Conf_OVC','Conf_Big Sky','Conf_Sun Belt','Conf_Big West','Conf_Summit',
            'Conf_A-Sun','Conf_Southern','Conf_CAA','Conf_MAC','Conf_AAC','Conf_MWC','Conf_A-10','Conf_Big East',
            'Conf_Big 12','Conf_Big Ten',
           'Region_East']
        }
    
    # > 0.00075
    round_drops_pre = {
        2:['Team','Round','Year','First_Year','Region','Wins','Conf Tourney',
           'Tempo','RankTempo','AdjTempo','DE','RankAdjTempo','RankOE',
           'Def_3','RankOff_1','RankDef_1','Def_1','Off_2','Off_1','RankDef_3','Def_2','RankOff_3','RankOff_2',
           'Off_3',
           'E8_Actual_12',
           'F4_Actual_6',
           'NCG_Actual_Full',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        3:['Team','Round','Year','First_Year',
           'AdjDE','RankAdjTempo','RankOE','RankAdjDE',
           'Def_2','Def_1',
           'R32_Actual_12','R32_Actual_6',
           'E8_Actual_12',
           'NCG_Actual_Full','NCG_Actual_6',
           'Winner_Actual_Full','Winner_Actual_6'],
        4:['Team','Round','Year','First_Year',
           'RankDE','RankAdjDE','RankTempo','OE',
           'Off_3','Off_2','Def_2','RankDef_3','Def_3',
           'R32_Actual_Full','R32_Actual_12','R32_Actual_6',
           'S16_Actual_Full',
           'E8_Actual_12','E8_Actual_6',
           'F4_Actual_Full',
           'NCG_Actual_6','NCG_Actual_12',
           'Winner_Actual_Full','Winner_Actual_12'],
        5:['Team','Round','Year','First_Year',
           'Tempo','DE','RankAdjTempo',
           'Off_3','RankOff_3','Off_2','RankDef_1',
           'F4_Actual_Full','F4_Actual_6',
           'R32_Actual_Full',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        6:['Team','Round','Year','First_Year','Conf Tourney','Seed',
           'DE','AdjEM',
           'RankOff_1','RankOff_2','Off_2','RankOff_3','Def_2','RankDef_1','Def_3','Off_1',
           'R32_Actual_12','R32_Actual_6',
           'S16_Actual_12','S16_Actual_6',
           'F4_Actual_6'],
        7:['Team','Round','Year','First_Year','Seed',
           'OE','RankDE','RankAdjDE','RankAdjOE','RankAdjEM',
           'Off_1','Def_3','Off_2','RankDef_2','RankDef_3','RankOff_2','Off_3','Def_1',
           'RankOff_3',
           'R32_Actual_Full',
           'S16_Actual_6',
           'E8_Actual_Full'],
    }
    round_drops_post = {
        2:['Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_Southland','Conf_ACC','Conf_Big 12','Conf_MAC',
           'Conf_CUSA','Conf_MAAC','Conf_Big South','Conf_SWAC','Conf_A-Sun','Conf_Sun Belt','Conf_Big West',
           'Conf_CAA','Conf_Big Sky','Conf_OVC','Conf_Summit','Conf_NEC','Conf_Big East','Conf_WCC',
           'Conf_AAC','Conf_A-10','Conf_Horizon','Conf_Ivy','Conf_MVC','Conf_SEC','Conf_WAC','Conf_Southern',
           'Conf_AEC','Conf_Patriot','Conf_Big Ten','Conf_Pac-12','Conf_MWC'],
       3:['Conf_MEAC','Conf_Mid-Cont','Conf_Southland','Conf_Pac-10','Conf_Patriot','Conf_A-Sun',
           'Conf_Big West','Conf_SWAC','Conf_CUSA','Conf_Sun Belt','Conf_NEC','Conf_AEC','Conf_MAC',
           'Conf_Southern','Conf_OVC','Conf_CAA','Conf_MAAC','Conf_Ivy','Conf_Horizon','Conf_Big South',
           'Conf_WAC','Conf_Summit','Conf_MWC','Conf_Big Sky','Conf_Big Ten','Conf_MVC','Conf_AAC',
           'Region_South'],
        4:['Conf_MVC','Conf_Southern','Conf_MAC','Conf_Pac-10','Conf_Southland','Conf_MEAC','Conf_Mid-Cont',
           'Conf_Big Ten','Conf_A-Sun','Conf_CAA','Conf_A-10','Conf_AEC','Conf_Patriot','Conf_CUSA','Conf_Big West',
           'Conf_MAAC','Conf_WAC','Conf_Big Sky','Conf_Big 12','Conf_MWC','Conf_NEC','Conf_Big South',
           'Conf_ACC','Conf_SWAC','Conf_Ivy','Conf_Summit','Conf_OVC','Conf_Sun Belt','Conf_AAC','Conf_Big East',
           'Region_Midwest','Region_South'],
        5:['Conf_Pac-12','Conf_Southland','Conf_Pac-10','Conf_Pac-10','Conf_MEAC','Conf_MAC','Conf_Patriot',
           'Conf_CUSA','Conf_Big Sky','Conf_Big West','Conf_Sun Belt','Conf_A-Sun','Conf_AEC','Conf_Summit',
           'Conf_WAC','Conf_MAAC','Conf_Big Ten','Conf_MVC','Conf_CAA','Conf_Big East','Conf_Ivy','Conf_NEC',
            'Conf_AAC','Conf_OVC','Conf_MWC','Conf_Big South','Conf_SWAC','Conf_Southern',
           'Region_West'],
        6:['Conf_CUSA','Conf_MVC','Conf_Southland','Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_MAC',
           'Conf_Big West','Conf_Summit','Conf_Big Sky','Conf_CAA','Conf_Sun Belt','Conf_A-Sun',
           'Conf_WAC','Conf_Patriot','Conf_MAAC','Conf_SWAC','Conf_Southern','Conf_Ivy','Conf_NEC','Conf_AEC',
            'Conf_Big South','Conf_OVC','Conf_AAC','Conf_MWC','Conf_ACC','Conf_A-10','Conf_Big 12','Conf_Big Ten',
           'Region_East','Region_South','Region_Midwest'],
        7:['Conf_Pac-12','Conf_CUSA','Conf_Patriot','Conf_SWAC','Conf_MAAC','Conf_AEC','Conf_Ivy','Conf_WAC',
           'Conf_NEC','Conf_Big South','Conf_Horizon','Conf_MVC','Conf_MEAC','Conf_Pac-10','Conf_Mid-Cont',
            'Conf_Southland','Conf_OVC','Conf_Big Sky','Conf_Sun Belt','Conf_Big West','Conf_Summit',
            'Conf_A-Sun','Conf_Southern','Conf_CAA','Conf_MAC','Conf_AAC','Conf_MWC','Conf_A-10','Conf_Big East',
            'Conf_Big 12','Conf_Big Ten',
           'Region_East']
        }
    
    # > 0.001
    round_drops_pre = {
        2:['Team','Round','Year','First_Year','Region','Wins','Conf Tourney',
           'Tempo','RankTempo','AdjTempo','DE','RankAdjTempo','RankOE',
           'Def_3','RankOff_1','RankDef_1','Def_1','Off_2','Off_1','RankDef_3','Def_2','RankOff_3','RankOff_2',
           'Off_3',
           'S16_Actual_12',
           'E8_Actual_12',
           'F4_Actual_12','F4_Actual_6',
           'NCG_Actual_Full','NCG_Actual_12','NCG_Actual_6',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        3:['Team','Round','Year','First_Year','Conf Tourney',
           'AdjDE','RankAdjTempo','RankOE','RankAdjDE','RankDE',
           'Def_2','Def_1','RankDef_2','RankDE',
           'R32_Actual_Full','R32_Actual_12','R32_Actual_6',
           'E8_Actual_12',
           'F4_Actual_Full','F4_Actual_12',
           'NCG_Actual_Full','NCG_Actual_12','NCG_Actual_6',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        4:['Team','Round','Year','First_Year','Wins',
           'RankDE','RankAdjDE','RankTempo','OE',
           'Off_3','Off_2','Def_2','RankDef_3','Def_3','RankOff_3','RankDef_2',
           'R32_Actual_Full','R32_Actual_12','R32_Actual_6',
           'S16_Actual_Full',
           'E8_Actual_12','E8_Actual_6',
           'F4_Actual_Full',
           'NCG_Actual_6','NCG_Actual_12',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        5:['Team','Round','Year','First_Year',
           'Tempo','DE','RankAdjTempo','AdjTempo',
           'Off_3','RankOff_3','Off_2','RankDef_1','RankDef_2','Def_3',
            'R32_Actual_Full','R32_Actual_6',
           'F4_Actual_Full','F4_Actual_6',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        6:['Team','Round','Year','First_Year','Conf Tourney','Seed',
           'DE','AdjEM','RankAdjEM',
           'RankOff_1','RankOff_2','Off_2','RankOff_3','Def_2','RankDef_1','Def_3','Off_1','Off_3',
           'R32_Actual_12','R32_Actual_6',
           'S16_Actual_12','S16_Actual_6',
           'F4_Actual_Full','F4_Actual_6'],
        7:['Team','Round','Year','First_Year','Seed',
           'OE','RankDE','RankAdjDE','RankAdjOE','RankAdjEM','AdjEM',
           'Off_1','Def_3','Off_2','RankDef_2','RankDef_3','RankOff_2','Off_3','Def_1',
           'RankOff_3',
           'R32_Actual_Full',
           'S16_Actual_Full','S16_Actual_6',
           'E8_Actual_Full','E8_Actual_12',
           'Winner_Actual_12'],
    }
    round_drops_post = {
        2:['Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_Southland','Conf_ACC','Conf_Big 12','Conf_MAC',
           'Conf_CUSA','Conf_MAAC','Conf_Big South','Conf_SWAC','Conf_A-Sun','Conf_Sun Belt','Conf_Big West',
           'Conf_CAA','Conf_Big Sky','Conf_OVC','Conf_Summit','Conf_NEC','Conf_Big East','Conf_WCC',
           'Conf_AAC','Conf_A-10','Conf_Horizon','Conf_Ivy','Conf_MVC','Conf_SEC','Conf_WAC','Conf_Southern',
           'Conf_AEC','Conf_Patriot','Conf_Big Ten','Conf_Pac-12','Conf_MWC'],
       3:['Conf_MEAC','Conf_Mid-Cont','Conf_Southland','Conf_Pac-10','Conf_Patriot','Conf_A-Sun',
           'Conf_Big West','Conf_SWAC','Conf_CUSA','Conf_Sun Belt','Conf_NEC','Conf_AEC','Conf_MAC',
           'Conf_Southern','Conf_OVC','Conf_CAA','Conf_MAAC','Conf_Ivy','Conf_Horizon','Conf_Big South',
           'Conf_WAC','Conf_Summit','Conf_MWC','Conf_Big Sky','Conf_Big Ten','Conf_MVC','Conf_AAC','Conf_WCC',
            'Conf_A-10',
           'Region_South'],
        4:['Conf_MVC','Conf_Southern','Conf_MAC','Conf_Pac-10','Conf_Southland','Conf_MEAC','Conf_Mid-Cont',
           'Conf_Big Ten','Conf_A-Sun','Conf_CAA','Conf_A-10','Conf_AEC','Conf_Patriot','Conf_CUSA','Conf_Big West',
           'Conf_MAAC','Conf_WAC','Conf_Big Sky','Conf_Big 12','Conf_MWC','Conf_NEC','Conf_Big South',
           'Conf_ACC','Conf_SWAC','Conf_Ivy','Conf_Summit','Conf_OVC','Conf_Sun Belt','Conf_AAC','Conf_Big East',
            'Conf_WCC',
           'Region_Midwest','Region_South'],
        5:['Conf_Pac-12','Conf_Southland','Conf_Pac-10','Conf_Pac-10','Conf_MEAC','Conf_MAC','Conf_Patriot',
           'Conf_CUSA','Conf_Big Sky','Conf_Big West','Conf_Sun Belt','Conf_A-Sun','Conf_AEC','Conf_Summit',
           'Conf_WAC','Conf_MAAC','Conf_Big Ten','Conf_MVC','Conf_CAA','Conf_Big East','Conf_Ivy','Conf_NEC',
            'Conf_AAC','Conf_OVC','Conf_MWC','Conf_Big South','Conf_SWAC','Conf_Southern','Conf_Big 12',
           'Region_West'],
        6:['Conf_CUSA','Conf_MVC','Conf_Southland','Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_MAC',
           'Conf_Big West','Conf_Summit','Conf_Big Sky','Conf_CAA','Conf_Sun Belt','Conf_A-Sun',
           'Conf_WAC','Conf_Patriot','Conf_MAAC','Conf_SWAC','Conf_Southern','Conf_Ivy','Conf_NEC','Conf_AEC',
            'Conf_Big South','Conf_OVC','Conf_AAC','Conf_MWC','Conf_ACC','Conf_A-10','Conf_Big 12','Conf_Big Ten',
            'Conf_SEC',
           'Region_East','Region_South','Region_Midwest'],
        7:['Conf_Pac-12','Conf_CUSA','Conf_Patriot','Conf_SWAC','Conf_MAAC','Conf_AEC','Conf_Ivy','Conf_WAC',
           'Conf_NEC','Conf_Big South','Conf_Horizon','Conf_MVC','Conf_MEAC','Conf_Pac-10','Conf_Mid-Cont',
            'Conf_Southland','Conf_OVC','Conf_Big Sky','Conf_Sun Belt','Conf_Big West','Conf_Summit',
            'Conf_A-Sun','Conf_Southern','Conf_CAA','Conf_MAC','Conf_AAC','Conf_MWC','Conf_A-10','Conf_Big East',
            'Conf_Big 12','Conf_Big Ten',
           'Region_East']
        }
    
    # > 0.002
    round_drops_pre = {
        2:['Team','Round','Year','First_Year','Region','Wins','Conf Tourney',
           'Tempo','RankTempo','AdjTempo','DE','RankAdjTempo','RankOE','OE','AdjDE',
           'Def_3','RankOff_1','RankDef_1','Def_1','Off_2','Off_1','RankDef_3','Def_2','RankOff_3','RankOff_2',
           'Off_3',
           'R32_Actual_Full','R32_Actual_12',
           'S16_Actual_Full','S16_Actual_12','S16_Actual_6',
           'E8_Actual_Full','E8_Actual_12',
           'F4_Actual_12','F4_Actual_6',
           'NCG_Actual_Full','NCG_Actual_12','NCG_Actual_6',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        3:['Team','Round','Year','First_Year','Conf Tourney','Wins',
           'AdjDE','RankAdjTempo','RankOE','RankAdjDE','RankDE','Tempo','RankAdjEM','AdjOE',
           'Def_2','Def_1','RankDef_2','Off_1','RankDef_1','RankOff_1',
           'R32_Actual_Full','R32_Actual_12','R32_Actual_6',
           'S16_Actual_Full','S16_Actual_12',
           'E8_Actual_Full','E8_Actual_12','E8_Actual_6',
           'F4_Actual_Full','F4_Actual_12','F4_Actual_6',
           'NCG_Actual_Full','NCG_Actual_12','NCG_Actual_6',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        4:['Team','Round','Year','First_Year','Wins',
           'RankDE','RankAdjDE','RankTempo','OE','DE','AdjDE','RankAdjTempo','AdjTempo',
           'Off_3','Off_2','Def_2','RankDef_3','Def_3','RankOff_3','RankDef_2','Def_1','RankOff_1',
           'RankDef_1','RankOff_2','Off_1',
           'R32_Actual_Full','R32_Actual_12','R32_Actual_6',
           'S16_Actual_Full',
           'E8_Actual_Full','E8_Actual_12',
           'F4_Actual_Full','F4_Actual_6',
           'NCG_Actual_6','NCG_Actual_12',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        5:['Team','Round','Year','First_Year',
           'Tempo','DE','RankAdjTempo','AdjTempo','RankTempo','RankOE',
           'Off_3','RankOff_3','Off_2','RankDef_1','RankDef_2','Def_3','Def_1','Off_1',
            'R32_Actual_Full','R32_Actual_6',
            'S16_Actual_Full',
           'F4_Actual_Full','F4_Actual_6',
           'NCG_Actual_12','NCG_Actual_6',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        6:['Team','Round','Year','First_Year','Conf Tourney','Seed','Region',
           'DE','AdjEM','RankAdjEM','RankAdjOE','RankAdjDE','RankOE','RankDE',
           'RankOff_1','RankOff_2','Off_2','RankOff_3','Def_2','RankDef_1','Def_3','Off_1','Off_3',
           'RankDef_2','RankOff_2','Def_1',
           'R32_Actual_Full','R32_Actual_12','R32_Actual_6',
           'S16_Actual_Full','S16_Actual_12','S16_Actual_6',
           'E8_Actual_6',
           'F4_Actual_Full','F4_Actual_12','F4_Actual_6',
           'NCG_Actual_Full','NCG_Actual_12',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        7:['Team','Round','Year','First_Year','Seed',
           'OE','RankDE','RankAdjDE','RankAdjOE','RankAdjEM','AdjEM',
           'AdjTempo','RankAdjTempo','AdjOE',
           'Off_1','Def_3','Off_2','RankDef_2','RankDef_3','RankOff_2','Off_3','Def_1',
           'RankOff_3','RankDef_3',
           'R32_Actual_Full',
           'S16_Actual_Full','S16_Actual_12','S16_Actual_6',
           'E8_Actual_Full','E8_Actual_12',
           'F4_Actual_Full','F4_Actual_12',
           'NCG_Actual_Full','NCG_Actual_12','NCG_Actual_6',
           'Winner_Actual_Full','Winner_Actual_12'],
    }
    round_drops_post = {
        2:['Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_Southland','Conf_ACC','Conf_Big 12','Conf_MAC',
           'Conf_CUSA','Conf_MAAC','Conf_Big South','Conf_SWAC','Conf_A-Sun','Conf_Sun Belt','Conf_Big West',
           'Conf_CAA','Conf_Big Sky','Conf_OVC','Conf_Summit','Conf_NEC','Conf_Big East','Conf_WCC',
           'Conf_AAC','Conf_A-10','Conf_Horizon','Conf_Ivy','Conf_MVC','Conf_SEC','Conf_WAC','Conf_Southern',
           'Conf_AEC','Conf_Patriot','Conf_Big Ten','Conf_Pac-12','Conf_MWC'],
       3:['Conf_MEAC','Conf_Mid-Cont','Conf_Southland','Conf_Pac-10','Conf_Patriot','Conf_A-Sun',
           'Conf_Big West','Conf_SWAC','Conf_CUSA','Conf_Sun Belt','Conf_NEC','Conf_AEC','Conf_MAC',
           'Conf_Southern','Conf_OVC','Conf_CAA','Conf_MAAC','Conf_Ivy','Conf_Horizon','Conf_Big South',
           'Conf_WAC','Conf_Summit','Conf_MWC','Conf_Big Sky','Conf_Big Ten','Conf_MVC','Conf_AAC','Conf_WCC',
            'Conf_A-10','Conf_Pac-12','Conf_ACC','Conf_Big 12',
           'Region_South','Region_East','Region_Midwest'],
        4:['Conf_MVC','Conf_Southern','Conf_MAC','Conf_Pac-10','Conf_Southland','Conf_MEAC','Conf_Mid-Cont',
           'Conf_Big Ten','Conf_A-Sun','Conf_CAA','Conf_A-10','Conf_AEC','Conf_Patriot','Conf_CUSA','Conf_Big West',
           'Conf_MAAC','Conf_WAC','Conf_Big Sky','Conf_Big 12','Conf_MWC','Conf_NEC','Conf_Big South',
           'Conf_ACC','Conf_SWAC','Conf_Ivy','Conf_Summit','Conf_OVC','Conf_Sun Belt','Conf_AAC','Conf_Big East',
            'Conf_WCC','Conf_Horizon',
           'Region_Midwest','Region_South','Region_East'],
        5:['Conf_Pac-12','Conf_Southland','Conf_Pac-10','Conf_Pac-10','Conf_MEAC','Conf_MAC','Conf_Patriot',
           'Conf_CUSA','Conf_Big Sky','Conf_Big West','Conf_Sun Belt','Conf_A-Sun','Conf_AEC','Conf_Summit',
           'Conf_WAC','Conf_MAAC','Conf_Big Ten','Conf_MVC','Conf_CAA','Conf_Big East','Conf_Ivy','Conf_NEC',
            'Conf_AAC','Conf_OVC','Conf_MWC','Conf_Big South','Conf_SWAC','Conf_Southern','Conf_Big 12',
           'Conf_Horizon','Conf_A-10',
           'Region_West','Region_Midwest','Region_East'],
        6:['Conf_CUSA','Conf_MVC','Conf_Southland','Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_MAC',
           'Conf_Big West','Conf_Summit','Conf_Big Sky','Conf_CAA','Conf_Sun Belt','Conf_A-Sun',
           'Conf_WAC','Conf_Patriot','Conf_MAAC','Conf_SWAC','Conf_Southern','Conf_Ivy','Conf_NEC','Conf_AEC',
            'Conf_Big South','Conf_OVC','Conf_AAC','Conf_MWC','Conf_ACC','Conf_A-10','Conf_Big 12','Conf_Big Ten',
            'Conf_SEC','Conf_Horizon'],
        7:['Conf_Pac-12','Conf_CUSA','Conf_Patriot','Conf_SWAC','Conf_MAAC','Conf_AEC','Conf_Ivy','Conf_WAC',
           'Conf_NEC','Conf_Big South','Conf_Horizon','Conf_MVC','Conf_MEAC','Conf_Pac-10','Conf_Mid-Cont',
            'Conf_Southland','Conf_OVC','Conf_Big Sky','Conf_Sun Belt','Conf_Big West','Conf_Summit',
            'Conf_A-Sun','Conf_Southern','Conf_CAA','Conf_MAC','Conf_AAC','Conf_MWC','Conf_A-10','Conf_Big East',
            'Conf_Big 12','Conf_Big Ten',
            'Region_East']
        }
    
    # > 0.003
    round_drops_pre = {
        2:['Team','Round','Year','First_Year','Region','Wins','Conf Tourney',
           'Tempo','RankTempo','AdjTempo','DE','RankAdjTempo','RankOE','OE','AdjDE',
           'Def_3','RankOff_1','RankDef_1','Def_1','Off_2','Off_1','RankDef_3','Def_2','RankOff_3','RankOff_2',
           'Off_3',
           'R32_Actual_Full','R32_Actual_12',
           'S16_Actual_Full','S16_Actual_12','S16_Actual_6',
           'E8_Actual_Full','E8_Actual_12','E8_Actual_6',
           'F4_Actual_Full','F4_Actual_12','F4_Actual_6',
           'NCG_Actual_Full','NCG_Actual_12','NCG_Actual_6',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        3:['Team','Round','Year','First_Year','Conf Tourney','Wins',
           'AdjDE','RankAdjTempo','RankOE','RankAdjDE','RankDE','Tempo','RankAdjEM','AdjOE',
           'OE','DE','RankAdjOE',
           'Def_2','Def_1','RankDef_2','Off_1','RankDef_1','RankOff_1','RankOff_2','Def_3',
           'Off_2','RankOff_3',
           'R32_Actual_Full','R32_Actual_12','R32_Actual_6',
           'S16_Actual_Full','S16_Actual_12',
           'E8_Actual_Full','E8_Actual_12','E8_Actual_6',
           'F4_Actual_Full','F4_Actual_12','F4_Actual_6',
           'NCG_Actual_Full','NCG_Actual_12','NCG_Actual_6',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        4:['Team','Round','Year','First_Year','Wins','Seed','Conf Tourney','Region',
           'RankDE','RankAdjDE','RankTempo','OE','DE','AdjDE','RankAdjTempo','AdjTempo','Tempo',
           'RankOE',
           'Off_3','Off_2','Def_2','RankDef_3','Def_3','RankOff_3','RankDef_2','Def_1','RankOff_1',
           'RankDef_1','RankOff_2','Off_1',
           'R32_Actual_Full','R32_Actual_12','R32_Actual_6',
           'S16_Actual_Full','S16_Actual_12','S16_Actual_6',
           'E8_Actual_Full','E8_Actual_12',
           'F4_Actual_Full','F4_Actual_6',
           'NCG_Actual_Full','NCG_Actual_12','NCG_Actual_6',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        5:['Team','Round','Year','First_Year','Wins',
           'Tempo','DE','RankAdjTempo','AdjTempo','RankTempo','RankOE','RankAdjOE',
           'Off_3','RankOff_3','Off_2','RankDef_1','RankDef_2','Def_3','Def_1','Off_1',
           'Def_2',
            'R32_Actual_Full','R32_Actual_12','R32_Actual_6',
            'S16_Actual_Full',
           'F4_Actual_Full','F4_Actual_6',
           'NCG_Actual_Full','NCG_Actual_12','NCG_Actual_6',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        6:['Team','Round','Year','First_Year','Conf Tourney','Seed','Region',
           'DE','AdjEM','RankAdjEM','RankAdjOE','RankAdjDE','RankOE','RankDE','Tempo','RankAdjTempo',
           'AdjDE','AdjOE','OE',
           'RankOff_1','RankOff_2','Off_2','RankOff_3','Def_2','RankDef_1','Def_3','Off_1','Off_3',
           'RankDef_2','RankOff_2','Def_1',
           'R32_Actual_Full','R32_Actual_12','R32_Actual_6',
           'S16_Actual_Full','S16_Actual_12','S16_Actual_6',
           'E8_Actual_6',
           'F4_Actual_Full','F4_Actual_12','F4_Actual_6',
           'NCG_Actual_Full','NCG_Actual_12',
           'Winner_Actual_Full','Winner_Actual_12','Winner_Actual_6'],
        7:['Team','Round','Year','First_Year','Seed',
           'OE','RankDE','RankAdjDE','RankAdjOE','RankAdjEM','AdjEM',
           'AdjTempo','RankAdjTempo','AdjOE',
           'Off_1','Def_3','Off_2','RankDef_2','RankDef_3','RankOff_2','Off_3','Def_1',
           'RankOff_3','RankDef_3',
           'R32_Actual_Full',
           'S16_Actual_Full','S16_Actual_12','S16_Actual_6',
           'E8_Actual_Full','E8_Actual_12',
           'F4_Actual_Full','F4_Actual_12','F4_Actual_6',
           'NCG_Actual_Full','NCG_Actual_12','NCG_Actual_6',
           'Winner_Actual_Full','Winner_Actual_12'],
    }
    round_drops_post = {
        2:['Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_Southland','Conf_ACC','Conf_Big 12','Conf_MAC',
           'Conf_CUSA','Conf_MAAC','Conf_Big South','Conf_SWAC','Conf_A-Sun','Conf_Sun Belt','Conf_Big West',
           'Conf_CAA','Conf_Big Sky','Conf_OVC','Conf_Summit','Conf_NEC','Conf_Big East','Conf_WCC',
           'Conf_AAC','Conf_A-10','Conf_Horizon','Conf_Ivy','Conf_MVC','Conf_SEC','Conf_WAC','Conf_Southern',
           'Conf_AEC','Conf_Patriot','Conf_Big Ten','Conf_Pac-12','Conf_MWC'],
       3:['Conf_MEAC','Conf_Mid-Cont','Conf_Southland','Conf_Pac-10','Conf_Patriot','Conf_A-Sun',
           'Conf_Big West','Conf_SWAC','Conf_CUSA','Conf_Sun Belt','Conf_NEC','Conf_AEC','Conf_MAC',
           'Conf_Southern','Conf_OVC','Conf_CAA','Conf_MAAC','Conf_Ivy','Conf_Horizon','Conf_Big South',
           'Conf_WAC','Conf_Summit','Conf_MWC','Conf_Big Sky','Conf_Big Ten','Conf_MVC','Conf_AAC','Conf_WCC',
            'Conf_A-10','Conf_Pac-12','Conf_ACC','Conf_Big 12','Conf_Big East',
           'Region_South','Region_East','Region_Midwest'],
        4:['Conf_MVC','Conf_Southern','Conf_MAC','Conf_Pac-10','Conf_Southland','Conf_MEAC','Conf_Mid-Cont',
           'Conf_Big Ten','Conf_A-Sun','Conf_CAA','Conf_A-10','Conf_AEC','Conf_Patriot','Conf_CUSA','Conf_Big West',
           'Conf_MAAC','Conf_WAC','Conf_Big Sky','Conf_Big 12','Conf_MWC','Conf_NEC','Conf_Big South',
           'Conf_ACC','Conf_SWAC','Conf_Ivy','Conf_Summit','Conf_OVC','Conf_Sun Belt','Conf_AAC','Conf_Big East',
            'Conf_WCC','Conf_Horizon','Conf_Pac-12'],
        5:['Conf_Pac-12','Conf_Southland','Conf_Pac-10','Conf_Pac-10','Conf_MEAC','Conf_MAC','Conf_Patriot',
           'Conf_CUSA','Conf_Big Sky','Conf_Big West','Conf_Sun Belt','Conf_A-Sun','Conf_AEC','Conf_Summit',
           'Conf_WAC','Conf_MAAC','Conf_Big Ten','Conf_MVC','Conf_CAA','Conf_Big East','Conf_Ivy','Conf_NEC',
            'Conf_AAC','Conf_OVC','Conf_MWC','Conf_Big South','Conf_SWAC','Conf_Southern','Conf_Big 12',
           'Conf_Horizon','Conf_A-10','Conf_ACC','Conf_WCC',
           'Region_West','Region_Midwest','Region_East'],
        6:['Conf_CUSA','Conf_MVC','Conf_Southland','Conf_MEAC','Conf_Mid-Cont','Conf_Pac-10','Conf_MAC',
           'Conf_Big West','Conf_Summit','Conf_Big Sky','Conf_CAA','Conf_Sun Belt','Conf_A-Sun',
           'Conf_WAC','Conf_Patriot','Conf_MAAC','Conf_SWAC','Conf_Southern','Conf_Ivy','Conf_NEC','Conf_AEC',
            'Conf_Big South','Conf_OVC','Conf_AAC','Conf_MWC','Conf_ACC','Conf_A-10','Conf_Big 12','Conf_Big Ten',
            'Conf_SEC','Conf_Horizon','Conf_Big East','Conf_WCC'],
        7:['Conf_Pac-12','Conf_CUSA','Conf_Patriot','Conf_SWAC','Conf_MAAC','Conf_AEC','Conf_Ivy','Conf_WAC',
           'Conf_NEC','Conf_Big South','Conf_Horizon','Conf_MVC','Conf_MEAC','Conf_Pac-10','Conf_Mid-Cont',
            'Conf_Southland','Conf_OVC','Conf_Big Sky','Conf_Sun Belt','Conf_Big West','Conf_Summit',
            'Conf_A-Sun','Conf_Southern','Conf_CAA','Conf_MAC','Conf_AAC','Conf_MWC','Conf_A-10','Conf_Big East',
            'Conf_Big 12','Conf_Big Ten',
            'Region_East']
        }